### ISSUE TITLE
A fater version of noise2d() for large images

### ISSUE THREAD

**Issue by AbdoKamel** [lmas/opensimplex#12]
Hi,

If that might be of interest for anyone, I have implemented a fast version of `noise2d()` for use in generating large noisy images. You may check it out in these commits:
https://github.com/AbdoKamel/opensimplex/commit/15bab4c7a2b12f52f4fe382c788002f5dd495578
https://github.com/AbdoKamel/opensimplex/commit/8f26f3ed37a6840fc3fdc271d3aecee05f4ebf2d

**Comment by lmas** [comment]
This is basically a duplicate of #4
