### ISSUE TITLE
Publish wheels on PyPI

### ISSUE THREAD

**Issue by rdb** [lmas/opensimplex#14]
Hi,

Thanks for making this great library!  It would be awesome if there could be [wheels](https://packaging.python.org/guides/distributing-packages-using-setuptools/#wheels) built and uploaded to PyPI.  This is as easy as:
```
python setup.py bdist_wheel
twine upload dist/opensimplex-0.3-py3-none-any.whl
```

Certain packaging/distribution tools require wheels to be available, since wheels do not require additional build steps and are easier to work with.

**Comment by lmas** [comment]
Hello and thanks!

Not that well versed in the python world anymore and last time I made an upgrade I didn't realize there were any obvious demand or usage of wheels so I simply skipped it.. Time to fix that! Once I get a free evening I'll upload a wheel for you.

**Comment by lmas** [comment]
btw, could I ask you what tools you are using that require wheels?

**Comment by rdb** [comment]
It's the [deployment tool](https://docs.panda3d.org/1.10/python/distribution/building-binaries) that ships with the Panda3D game engine.  This tool builds an executable out of a Python game for any desired target platform.  It requires wheels to be available because it is unable to build packages by itself—largely because it's not possible to compile packages for other platforms, although I suppose that's less relevant for pure-Python packages.

**Comment by lmas** [comment]
Alright thanks, always interesting to learn about new use cases :+1: 

Offtopic: It is a little bit weird for me, as I see it's using good ol' pip in the background, but still enforces binary pkgs only. 
(But like I said, completely out of sync with the current python ecosystem heh)

**Comment by rdb** [comment]
Yeah, it might be a good feature request for Panda3D to support building pure-Python packages from sdist.  (Though there are some caveats there, such as that it's not trivial to know for sure whether a package will be pure-Python before extracting it and executing its setup.py.)

Another reason some users prefer installing from whl is that it avoids executing arbitrary thirdparty code (ie. setup.py) at install time.  This may be especially relevant when installing packages system-wide, as root.

**Comment by lmas** [comment]
Hmm yeah good point, that is a valid concern with running setup.py as root. 

I'll see if I can kick this issue higher up on my todo list for this weekend :)

**Comment by lmas** [comment]
All done and uploaded wheels, enjoy
