### ISSUE TITLE
Range of noise result

### ISSUE THREAD

**Issue by mfbehrens99** [lmas/opensimplex#18]
Hi, I was wondering what the range of the nose functions are. It doesn't say that anywhere in the documentation, and I am not reaching values above `0.8`

**Comment by pmbaumgartner** [comment]
Also curious. I sampled in 2d, 3d, and 4d and got 3 different ranges...

```python
import numpy as np
from opensimplex import OpenSimplex
simplex_noise = OpenSimplex(seed=64)

space_simplex = np.linspace(0, 50000, 100000)
d2 = []
d3 = []
d4 = []
for n in space:
    d2.append(simplex_noise.noise2d(n, n))
    d3.append(simplex_noise.noise3d(n, n, n))
    d4.append(simplex_noise.noise4d(n, n, n, n))


print(min(d2), max(d2))
print(min(d3), max(d3))
print(min(d4), max(d4))
```
```
-0.8068300440424511 0.8066848690415231
-0.8641346043372317 0.8318555257199642
-0.701573878396019 0.721489191242297
```

**Comment by mfbehrens99** [comment]
Is there a reason why the ranged differ depending on the dimension of the noise?

btw in the line with the for look in your code you should write `for n in space_simplex`.  Just if somebody else is going to test it aswell ;)

**Comment by pmbaumgartner** [comment]
> btw in the line with the for look in your code you should write `for n in space_simplex`. Just if somebody else is going to test it aswell ;)

Whoops, you're right. Should be corrected.

The range changing with the dimension was just another artifact I noticed too. I'm not sure why it would change depending on the dimension. I tried the same thing with "faux" 1d noise by replacing all the other `n`s with 0 as well, similar results on the range.

**Comment by lmas** [comment]
Huh never tested the ranges before... Gotta research how other implementations behaves (preferably in other languages).
I also remember something about fixed artefacts in the new opensimplex2, from the original creator `KdotJPG`, so maybe it's already been fixed.

I've been waiting for him to finalize his new version before I update this package (see #15, no planned release date, sorry), so I might want to put this issue on hold until the update is done.

**Comment by lmas** [comment]
As a super quick test in golang:
```
package main

import (
        "fmt"

        "github.com/ojrac/opensimplex-go"
)

func main() {
        var d2, d3, d4 []float64
        noise := opensimplex.New(64)

        for _, f := range linspace(0, 50000.0, 100000.0) {
                d2 = append(d2, noise.Eval2(f, f))
                d3 = append(d3, noise.Eval3(f, f, f))
                d4 = append(d4, noise.Eval4(f, f, f, f))
        }

        fmt.Println(min(d2), max(d2))
        fmt.Println(min(d3), max(d3))
        fmt.Println(min(d4), max(d4))
}

// basically stolen from: https://github.com/numpy/numpy/blob/v1.20.0/numpy/core/function_base.py#L23-L175
func linspace(start, stop, num float64) []float64 {
        delta := stop - start
        step := delta / (num - 1)
        var list []float64
        for f := start; f < stop; f += step {
                list = append(list, f)
        }
        return list
}

func min(list []float64) float64 {
        min := 0.0
        for _, f := range list {
                if f < min {
                        min = f
                }
        }
        return min
}

func max(list []float64) float64 {
        max := 0.0
        for _, f := range list {
                if f > max {
                        max = f
                }
        }
        return max
}
```

```
-0.8068650767446498 0.8068659141482294
-0.8642550300387978 0.8642461955672212
-0.7021124879438775 0.7214975540064487
```
the results are close enough, so it might be algorithm artefact?

**Comment by endolith** [comment]
@pmbaumgartner 

> Also curious. I sampled in 2d, 3d, and 4d and got 3 different ranges...

They have different probability distributions, too.

![opensimplex noise PDF spectrum](https://user-images.githubusercontent.com/58611/110723957-edf85900-81e2-11eb-9135-518581f3eab7.png)


Though this seems to just be a property of the noise: https://computergraphics.stackexchange.com/q/4212/15908

**Comment by pmbaumgartner** [comment]
@endolith This is really interesting, thanks for sharing. Outside of the scope of this issue, but do you know how folks use simplex noise with interpolation? One of the nice features of knowing the range of noise values is being able to map their output (e.g. 0-1 w/ perlin noise) to some other domain that makes sense for the next function.

**Comment by endolith** [comment]
@pmbaumgartner Not sure I understand the question?  From what I was reading, Perlin and simplex noise are specifically designed to be cheap to evaluate at any arbitrary coordinates, so they can be applied to triangular meshes for 3d modeling, etc.

**Comment by pmbaumgartner** [comment]
Sure. With perlin noise, I know the range (i.e. output) of the function is between 0 and 1. Because I know this, I can interpolate the output noise value to another known range. For example, you could map the values from 0 to 1 to radial coordinates by mapping it from 0 to 2*PI to translate the noise value to a direction on the unit circle (i.e. an angle).

With simplex noise, if I wanted radial noise, since I don't know the range of the function I couldn't do that. I'd have to choose a ballpark number like -0.8 to +0.8, but in the angular case with a circle I'd probably get overlapping values somewhere since I don't know exactly what that output range is.

Does that make sense? I can try and find more examples, but that was just a use case that came to the top of my head.

**Comment by endolith** [comment]
@pmbaumgartner  Oh, ok.  Yeah I don't know what the range is.  You'd have to look at the possible gradients and what they combine to when all neighbors are in the most extreme case?  https://weber.itn.liu.se/~stegu/simplexnoise/simplexnoise.pdf  It's not uniformly distributed, though, so I don't think it would work as well for an angular thing like that?  Also I think it varies by implementation, like that document says "A good choice for 2D and higher is to pick gradients of unit length but different directions. For 2D, 8 or 16 gradients distributed around the unit circle is a good choice."  So it's up to the implementation which ones are chosen and that would determine how they sum.  (I don't really understand the algorithm beyond that.)

**Comment by arnauddupuis** [comment]
I'm a bit late to the party but isn't Perlin noise supposed to range from -1/2*sqrt(number of dimensions) to +1/2*sqrt(number of dimensions). Not -1/+1. For 2D noise it would be around +/- 0.7, I haven't looked much at the math differences between Perlin and Simplex (on my todo list) but it seem consistent.

**Comment by lmas** [comment]
@arnauddupuis That's interesting. It's actually part of the [source](https://github.com/lmas/opensimplex/blob/master/opensimplex/opensimplex.py#L16)

**Comment by arnauddupuis** [comment]
@lmas I feel silly now :sweat_smile: it should be obvious by now that I haven't read your code... sorry.
This ticket is a very interesting discussion but I am not sure that it should be labeled as a bug. 
I'm looking forward for your OS2F implementation! Thanks a lot for your work!!!

**Comment by lmas** [comment]
@arnauddupuis Noo I wasn't bashing you or anything, your comment helped explain that chunk of constants! And why we were getting this limited range of noise :smile: (I've said it before, 4D matrix math is way out of my capabilities)

Also agree it's not really a bug anymore, it's more of an algorithm detail. I'll keep this issue open for a bit longer to let people discuss it further if they want to and for me to post more results of the new versions if it's of interest.
