### ISSUE TITLE
3D noise repeats itself

### ISSUE THREAD

**Issue by endolith** [lmas/opensimplex#19]
Maybe this is just the way the algorithm works, but neither 2D nor 4D noise repeat themselves, so it seems odd to me.

![3d is repetitive Figure_0](https://user-images.githubusercontent.com/58611/110724866-8ba05800-81e4-11eb-8419-7d8fbafe1167.png)

```
tmp = OpenSimplex()
N = 100_000
x_max = 5000
t = np.linspace(0, x_max, N)
for x in t:
    out_2d.append(tmp.noise2d(x=x, y=y))
    out_3d.append(tmp.noise3d(x=x, y=y, z=0))
    out_4d.append(tmp.noise4d(x=x, y=y, z=0, w=0))
```

**Comment by lmas** [comment]
Yeah feels more like it's part of the algo. Really gotta compare the results from other libraries and languages.

Thanks for the notice! Going to close this one though, as it's too similar in scope to #18, sorry
