### ISSUE TITLE
version .04 docs

### ISSUE THREAD

**Issue by lonce** [lmas/opensimplex#21]
>>> import opensimplex
>>> opensimplex.seed(1234)
>>> n = opensimplex.noise2(x=10, y=10)
>>> print(n)
    0.580279369186297

This doesn't work since the "module object is not callable"

I find the old method works (except for the change of function name):

from opensimplex import OpenSimplex
simplex=OpenSimplex(seed=1234)
n = simplex.noise2(x=10, y=10)

**Comment by lmas** [comment]
```
Python 3.8.12 (default, Nov  4 2021, 01:12:24) 
[Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c on freebsd13
Type "help", "copyright", "credits" or "license" for more information.
>>> import opensimplex
>>> opensimplex.seed(-13)
>>> opensimplex.noise3(-1, 2, 300)
-0.3676535219145857
```

Had a hunch it worked too easy for me? But now I'm happy that I left the previous calling method "just in case", so you could still use the library at least.

I probably need more info from you, for starters what python version?

**Comment by lmas** [comment]
Closing due to no reply for now, feel free to reopen it again.
