### ISSUE TITLE
Weird output.

### ISSUE THREAD

**Issue by GAZ082** [lmas/opensimplex#3]
Hello there. I made a SO question which perhaps could be replied here or there:

http://stackoverflow.com/questions/40894473/opensimplex-issues

Thanks a lot.

**Comment by lmas** [comment]
Hi, I don't have an account on SO but I could help you here instead. 

Please paste a full source code and python version, so I could try to run your code and check the result myself.

**Comment by GAZ082** [comment]
from opensimplex import OpenSimplex
import numpy as np

def simplex_noise(size):
    def noise(nx, ny):
        gen = OpenSimplex()
        # Rescale from -1.0:+1.0 to 0.0:1.0
        return gen.noise2d(nx, ny) / 2.0 + 0.5 

    value = np.zeros((size,size),dtype=np.float16)

    for y in range(size):
        for x in range(size):
            nx = x/size - 0.5
            ny = y/size - 0.5
            value[y,x] = noise(nx, ny) #(dont ask why flips x-y)

    return value.reshape(size * size).tolist();

Thanks a lot!

BTW, you may check SO thread for more info and pictures, dont need an account for that.

**Comment by GAZ082** [comment]
Python 3.5

**Comment by lmas** [comment]
Yeah I know about SO ;) thanks for the version, but the source you've provided doesn't render any pics for me so I can't compare my results with yours.

I did try running:
```
    for y in range(size):
        for x in range(size):
            nx = x/size - 0.5
            ny = y/size - 0.5
            value[y,x] = noise(nx, ny)
            print(nx, ny, value[y,x] # shows OK values, getting 2d noise here

    return value.reshape(size * size).tolist()

print(simplex_noise(10)) # also shows OK values, with random 2d noise values
```

**Comment by lmas** [comment]
You shouldn't run `gen = OpenSimplex()` all the time in that noise func, it's meant to be declared only once and then reused. Setting a new, random seed is preferably too, but not required, to get good noise values.

I don't know if this is the issue, since I can't compare results with you yet.

**Comment by GAZ082** [comment]
Thanks for spotting that. Been doing some tests and after using your example i tested that not just random values are output'ed but that they are actuall noise, so the issue is not your awesome library.

Thanks a lot for your time and the lib.

**Comment by lmas** [comment]
Sure thing man. 

There's a bunch of unit tests in this repo that you can run too (`make test`), if you think you're getting bad results from the lib itself and need to verify it.
