### ISSUE TITLE
Add ability to get the currently set seed value

### ISSUE THREAD

**Issue by derpsticks** [lmas/opensimplex#39]
Please add a function or attribute that allows for the retrieval of the currently set seed value.

**Comment by lmas** [comment]
Hi, this is easily done. But any particular motivation for having it done in the library and not in your own code? Just curious.

**Comment by derpsticks** [comment]
In general it is better to have a single source of truth about a particular setting or variable. Relying on each project to save and track seed values in their own unique way leads to the possibility of error or bugs, whereas if it is just a simple and reliable call to the module itself there is no possibility of error.

**Comment by lmas** [comment]
I think if you're able to set up any kind of state in a project, it shouldn't be difficult to track a single integer that was used once.
Just curious though, not looking to start an argument.

Is #40 good enough?

**Comment by lmas** [comment]
Merged and closed due to inactivity.
