### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by MuellerSeb** [lmas/opensimplex#42]
Hi,

it would be nice, to have opensimplex on conda-forge. I wanted to create a recipe there but noticed, that I can't run the tests due to #41 . 

Are you ok with me creating a recipe? I would add you as a maintainer there, so you get access.

Cheers,
Sebastian

**Comment by lmas** [comment]
Hi thanks for asking, appreciate it! I don't use it so feel free to do whatever.

-- 
Alex

----------------------------------------

14 Feb 2023 22:10:17 Sebastian Müller ***@***.***>:

**Comment by MuellerSeb** [comment]
Please add a comment here that you are fine with being listed as author in the conda-package feestock: https://github.com/conda-forge/staged-recipes/pull/23863
