### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by TWang1017** [lmas/opensimplex#44]
Hi, Thanks for the great work!

Im trying to integrate the simplex noise into my pytorch pipeline, but it is not gpt-supported and i have to loop hundred of thousand times to create noise for my img, any idea how to accelerate it in pytorch?

**Comment by lmas** [comment]
Hiya, sorry no idea. Doesn't seem like pytorch supports FreeBSD (still) so I haven't been able to even install it in the last couple of years.

**Comment by Julian-Wyatt** [comment]
@lmas Would you be happy if I looked into adding PyTorch support for your library?

**Comment by lmas** [comment]
@Julian-Wyatt Thanks for the offer and for asking beforehand (!), but no thanks.
I don't want to be personally responsible for or spend maintenance time on code/features (with low demand) I can't run on my own systems.

If you need performance you should stop using Python and find some other language with related tools, libraries or C bindings.

*(on a semi-related note, I should clarify I'm also supporting FreeBSD in the README)*
