### ISSUE TITLE
Different values on different os

### ISSUE THREAD

**Issue by PetyaVasya** [lmas/opensimplex#7]
Hi. I'm bad speak on eng, sry. But your program return different values on Windows and MacOS.
I use c_int64 instead c_long. And fix this issue. Mb I'm dumb, help me) for right solve

**Comment by PetyaVasya** [comment]
https://github.com/lmas/opensimplex/blob/05556e8844e32ff0472f7f562954834d031dc668/opensimplex/opensimplex.py#L81

**Comment by lmas** [comment]
Hello and thanks for commenting. I'll try to look at this issue this weekend.

Have you tried to run the tests? Or what does your output values look like?

**Comment by PetyaVasya** [comment]
I'm creating a game now and I push seed to my users. And get difference maps.
You can init your class and get equals tile and get difference values on differences os.
sorry for bad English)

**Comment by lmas** [comment]
It is ok :+1: 
I managed to get some wrong output too on Windows.

Verified your fix, using `c_int64`, and it seems to be all good now. Thanks for telling me!
